services:
  app:
    image: connermo/docker-pull:latest
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./downloads:/app/backend/downloads
    environment:
      # 代理配置（一个变量搞定所有代理设置）
      - DOCKER_PROXY=${DOCKER_PROXY:-}
      - DOCKER_REGISTRY_MIRROR=${DOCKER_REGISTRY_MIRROR:-}
      
    restart: unless-stopped

networks:
  default:
    driver: bridge 